auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifedump_dir: /tmp/loki/lifedump
  max_chunk_age: 1h
  chunk_idle_period: 30m

schema_config:
  configs:
    - from: 2020-05-15
      store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 3600

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s