global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['blue:3000', 'green:3001']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']
    metrics_path: '/metrics'
    scheme: http

rule_files:
  - rules/*.rules

remote_write:
  - url: http://loki:3100/api/prom/push