name: Backup MongoDB to AWS S3 Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region = us-east-1" > ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: SSH Into Server & Run Backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            if [ ! -d "todo-devops-suite" ]; then
              git clone https://github.com/Sachin-960/todo-devops-suite.git  todo-devops-suite
            else
              cd todo-devops-suite && git pull origin main
            fi

            # Make scripts executable
            chmod +x todo-devops-suite/scripts/*.sh

            # Run DB backup
            cd todo-devops-suite
            ./scripts/backup.sh